name: checkout tagged commits

on:
  workflow_dispatch:

jobs:
  prepare-tags:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.collect.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: true

      - name: Collect tags oldest to newest
        id: collect
        shell: bash
        run: |
          git for-each-ref --sort=creatordate --format='%(refname:short) %(objectname)' "refs/tags/v*" --exclude='refs/tags/*-*'  \
              | tail -n 2 \
              | python3 -c 'import json;import sys; print("matrix="+json.dumps({"include": [{"tag": tag, "commit": sha} for tag, sha in [p.split() for p in sys.stdin]+[("master", "master")]]}))' \
                >> $GITHUB_OUTPUT

  checkout-tags:
    runs-on: ubuntu-22.04
    needs: prepare-tags
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-tags.outputs.matrix) }}
    permissions:
      contents: read
    steps:
      - name: Checkout tag commit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ matrix.commit }}
          fetch-depth: 1

      - name: Checkout perftest folder from main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 1
          sparse-checkout: |
            perftest

      - name: Run test script from main
        run: |
          echo "Tag: ${{ matrix.tag }}"
          echo "Commit: ${{ matrix.commit }}"
          ls
