name: PR managed comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-and-upsert-comment:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout latest master
        uses: actions/checkout@v4
        with:
          ref: 'master'
          path: master

      - name: Checkout pr head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-head

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          cmake: true

      - name: Build latest master and PR head
        id: build
        run: |
          mkdir -p builds
          if [ ! -d builds/master ]; then
            cmake -B builds/master -S master -DFINUFFT_BUILD_TESTS=ON &&
            cmake --build builds/master --target perftest -j
          fi
          if [ ! -d builds/pr-head ]; then
            cmake -B builds/pr-head -S pr-head -DFINUFFT_BUILD_TESTS=ON &&
            cmake --build builds/pr-head --target perftest -j
          fi
          pip install pandas matplotlib
          python3 master/perftest/collect_dual_perftest.py \
            --master-perftest builds/master/perftest/perftest \
            --pr-perftest builds/pr-head/perftest/perftest \
            --plot-output master/perftest_comment_figure.png

          git -C master branch -D orphan-new || true && git -C finufft switch --orphan orphan-new
          git -C master add perftest_comment_figure.png
          PRE_COMMIT_ALLOW_NO_CONFIG=1 git -C master commit -m "Performance change [no ci]"
          IMAGE_SHA=$(git -C master rev-parse HEAD)
          echo $IMAGE_SHA
          git -C master push
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_OUTPUT

      - name: Find existing managed comment
        if: always()
        id: find-comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "<!-- pr-managed-comment -->"

      - name: Create managed PR comment
        if: always() && steps.find-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <!-- pr-managed-comment -->
            ${{ steps.build.outputs.image_sha }}

      - name: Update managed PR comment
        if: always() && steps.find-comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- pr-managed-comment -->
            ${{ steps.build.outputs.image_sha }}
