name: Test Consumer

on:
  workflow_dispatch:


jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: finufft-wheels-manylinux_x86_64
          github-token: ${{ github.token }}
          run-id:  24074274002
          path: ./artifacts

      - name: Print artifact content
        run: |
          echo "Artifact content retrieved:"
          ls -la ./artifacts

      - name: Install finufft from artifact
        run: |
          pip install --upgrade pip
          pip install ./artifacts/finufft-2.6.0.dev0-py3-none-manylinux_2_28_x86_64.whl
