name: Test Consumer

on:
  workflow_dispatch:


jobs:
  consume:
    runs-on: ubuntu-latest
    steps:

      - name: Check if commit already has perf tag
        id: check_tag
        run: |
          if git tag --points-at HEAD | grep -q "perf"; then
            exit 0
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: finufft-wheels-manylinux_x86_64
          github-token: ${{ github.token }}
          run-id:  24074274002
          path: ./artifacts

      - name: Install finufft from artifact
        run: |
          pip install --upgrade pip
          pip install ./artifacts/finufft-2.6.0.dev0-py3-none-manylinux_2_28_x86_64.whl
          pip install pandas

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Run perftest
        if: steps.check_tag.outputs.has_perf_tag == 'false'
        run: |
          python perftest/perftest.py $(git rev-parse --short HEAD) perftest_results.csv

      - name: Configure git
        if: steps.check_tag.outputs.has_perf_tag == 'false'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push perftest results
        run: |
          git add perftest_results.csv
          git commit -m "Add perftest results for"
          git tag "perf"
          git push
          git push --tags
